customhost = "employee.czjxsaypn7iz.ap-south-1.rds.amazonaws.com"
customuser = "indrajit"
custompass = "indrajit"
customdb = "employee"
custombucket = "addemployeeindrajit"
customregion = "ap-south-1"
